### ISSUE TITLE
数据，下不了

### ISSUE THREAD

**Issue by wanghaoran-ucas** [neuChatbotDS/emoElicitorData#1]
Google 云端硬盘无法为此文件查毒。
export.json.zip (270M) 文件过大，Google 无法扫描病毒。是否仍要下载此文件？

这数据下载不了

**Comment by valar000** [comment]
![image](https://user-images.githubusercontent.com/12813872/82808686-0bab3a80-9ebd-11ea-9c5e-c669f00efd4f.png)
直接下载不要管警告

**Comment by wanghaoran-ucas** [comment]
也下载不了，早就试了

**Comment by wanghaoran-ucas** [comment]
点了也下载不了 @valar000

**Comment by valar000** [comment]
我百度网盘再传一份

**Comment by valar000** [comment]
因为百度网盘没开会员要等一会了 @wanghaoran-ucas ,能否提供下载问题(截图),我开chrome隐身能下载

**Comment by wanghaoran-ucas** [comment]
就是你上面那个截图，点了‘仍然下载’，一直缓冲转圈，没反应

**Comment by valar000** [comment]
那就是网的问题了,等百度网盘链接吧

**Comment by wanghaoran-ucas** [comment]
如图

**Comment by valar000** [comment]
@wanghaoran-ucas  done

**Comment by wanghaoran-ucas** [comment]
OK，非常感谢

**Comment by wanghaoran-ucas** [comment]
老师，您好，非常感谢昨天提供的百度云数据链接，你们这数据集很有意义。有三个疑问想请教您：
1.PPT直播中我看每轮用一个特定的情感e来控制下一句对话的生成，但是每轮对话有好几个emoji，怎么选择划分到特定的情感
2. 有些对话没有emoji（即没有相应的情感），怎么处理？还是直接不管它?
3对话中有有很多@user，实际对话应该没有，处理的时候是把它们删掉吗？

**Comment by valar000** [comment]
新问题开在其他issue
